import type { Metadata } from "next";
import { Inter } from "next/font/google";
import header from "@/app/components/app.header";
import table from "@/app/components/app.table";
import AdvancedExample from "@/app/components/app.footer";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header />
        {children}
        {/* <footer>{footer}</footer> */}
        <footer />
      </body>
    </html>
  );
}
